"""AuthEngine — API key authentication + RBAC + rate limiting for T121/T125.

Security rules:
- Every request must carry a valid X-API-Key header
- Keys are generated by admin and stored in-memory + JSONL
- Each key is associated with a role: observer, operator, reviewer, admin
- Rate limiting: 60 requests per minute per key
- Audit log: every request is logged with timestamp, user_id, role, endpoint, outcome
"""

import json
import time
from collections import deque
from pathlib import Path
from typing import Any, Dict, List, Optional, Set


class AuthEngine:
    """Manages API keys, roles, rate limiting, and audit logging."""

    VALID_ROLES: Set[str] = {"observer", "operator", "reviewer", "admin"}

    def __init__(self, data_root: str = "data/web_gateway") -> None:
        self.data_root = Path(data_root)
        self.data_root.mkdir(parents=True, exist_ok=True)
        self._keys: Dict[str, str] = {}  # key -> role
        self._rate_window_seconds: float = 60.0
        self._rate_max_requests: int = 60
        self._request_log: Dict[str, deque] = {}
        self._audit_path = self.data_root / "audit.jsonl"
        self._keys_path = self.data_root / "keys.jsonl"
        self._load_keys()

    # ------------------------------------------------------------------ #
    # Key management
    # ------------------------------------------------------------------ #

    def _load_keys(self) -> None:
        if not self._keys_path.exists():
            return
        with open(self._keys_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                    action = record.get("action")
                    key = record.get("key")
                    role = record.get("role", "observer")
                    if not key:
                        continue
                    if action == "add_key":
                        self._keys[key] = role
                    elif action == "revoke_key":
                        self._keys.pop(key, None)
                except (json.JSONDecodeError, KeyError):
                    continue

    def generate_key(self, role: str = "observer") -> str:
        """Generate a new API key with the given role and persist it."""
        if role not in self.VALID_ROLES:
            raise ValueError(f"Invalid role {role}. Must be one of {self.VALID_ROLES}")
        import secrets

        key = secrets.token_urlsafe(32)
        self._keys[key] = role
        self._persist_key_action("add_key", key, role=role)
        return key

    def revoke_key(self, key: str) -> bool:
        """Revoke an existing API key."""
        removed = key in self._keys
        self._keys.pop(key, None)
        if removed:
            self._persist_key_action("revoke_key", key)
        return removed

    def _persist_key_action(self, action: str, key: str, role: Optional[str] = None) -> None:
        record: Dict[str, Any] = {
            "action": action,
            "key": key,
            "timestamp": time.time(),
        }
        if role is not None:
            record["role"] = role
        with open(self._keys_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(record) + "\n")

    def is_valid(self, key: str) -> bool:
        return key in self._keys

    def get_role(self, key: str) -> Optional[str]:
        return self._keys.get(key)

    def list_keys(self) -> List[Dict[str, Any]]:
        """Return list of active keys with roles (key value redacted for security)."""
        return [
            {
                "key_preview": f"{k[:8]}...",
                "role": role,
            }
            for k, role in self._keys.items()
        ]

    # ------------------------------------------------------------------ #
    # Rate limiting
    # ------------------------------------------------------------------ #

    def check_rate_limit(self, key: str) -> bool:
        now = time.time()
        log = self._request_log.setdefault(key, deque())
        # Remove entries outside the window
        while log and log[0] < now - self._rate_window_seconds:
            log.popleft()
        if len(log) >= self._rate_max_requests:
            return False
        log.append(now)
        return True

    # ------------------------------------------------------------------ #
    # Audit log
    # ------------------------------------------------------------------ #

    def audit(
        self,
        key: str,
        endpoint: str,
        method: str,
        status: int,
        client_ip: str = "unknown",
        role: Optional[str] = None,
        user_id: Optional[str] = None,
    ) -> None:
        record: Dict[str, Any] = {
            "timestamp": time.time(),
            "user_id": user_id or key,
            "key_preview": f"{key[:8]}..." if len(key) > 8 else key,
            "role": role or self.get_role(key) or "unknown",
            "endpoint": endpoint,
            "method": method,
            "status": status,
            "client_ip": client_ip,
        }
        with open(self._audit_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(record) + "\n")
